name: elura_skincare_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.28.0  # Key: Use a version that provides PromiseJsImpl
  firebase_auth: ^4.19.0  # This version pairs with the core version above[citation:8]
  # Your other dependencies...
  http: ^1.1.0
  geolocator: ^9.0.2
  cupertino_icons: ^1.0.8
  google_fonts: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Remove or use older flutter_lints:
  flutter_lints: ^2.0.0      # Older version

flutter:
  uses-material-design: true
  assets:
    - assets/images/